### ISSUE TITLE
missing icons in eww bar

### ISSUE THREAD

**Issue by 1ilir0lika** [smravec/.dotfiles-hyprland#1]
# error:
**After I installed your eww config,instead of having icons,I have some strange unicode characters**
![20221216_13h28m51s_grim](https://user-images.githubusercontent.com/49962713/208098451-45e55e29-786f-4236-b4e1-69195a9b61a8.png)

**Comment by smravec** [comment]
To fix this you should install ttf-material-design-icons from the aur. If you are not using arch based distro check out their website here: https://materialdesignicons.com/

**Comment by smravec** [comment]
also if you are using this eww config without the other stuff in my dotfiles most of the features wont work so use it just as inspiration and build from it your own.

**Comment by 1ilir0lika** [comment]
After I installed the package(using the aur) I still see the missing icons

**Comment by smravec** [comment]
when installing any font you should then run ```fc-cache -fv``` and reboot. If that does not work you probably have some  conflicts with other fonts (I know I had issues with nerdfonts)
